### ISSUE TITLE
searching for a location: text input stops when suggestion was found

### ISSUE THREAD

**Issue by DaThaoTran** [Arvernus/arvernus-apple-maps-block#13]
**Describe the bug**
When you're searching for an address, while typing the text input would stop when a suggestion for your address was found - even if you're in the middle of entering a word. You have to click on the search field again to continue entering your exact location (which can very much differ from the suggested address/location). 

**To Reproduce**

1. Go to 'Location Settings'
2. Click on 'Search'
3. Enter any address 

**Expected behavior**
The suggestions should only appear and be selectable when clicked. The text input process shouldn't be interrupted. 

**Desktop (please complete the following information):**

- OS: [iOS]
- Browser [safari]
- Version [12.0.3]

**Additional context**
Version Plug-in: 1.0.1

**Comment by fabiankaegy** [comment]
should be solved in 1.0.8
