### ISSUE TITLE
frontend doesn't display block correctly

### ISSUE THREAD

**Issue by DaThaoTran** [Arvernus/arvernus-apple-maps-block#5]
**Describe the bug**
Regardless whether some settings are changed or not, the frontend always shows the block as a squared area. You cannot see the map itself.

**To Reproduce**

1. Create an arvernus apple maps block
2. Click on 'preview' 
3. See error

**Expected behavior**
The frontend should look like the backend, showing an actual map.

**Screenshots**
![Bildschirmfoto 2019-04-05 um 14 35 04](https://user-images.githubusercontent.com/47741998/55628757-d243d700-57b1-11e9-8979-483b572e57ad.png)

**Desktop (please complete the following information):**

- OS: [ iOS]
- Browser [safari]
- Version [12.0.3]

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/829536738800055/1117398941783685)

**Comment by fabiankaegy** [comment]
This error only happens if the permalink is set to something custom, because the rest api endpoint its not located in the correct place. I will try and change all my API calls to use the wp-fetch function instead. Maybe that automatically resolves the url.

Otherwise I'll have to see what else we can do.

**Comment by fabiankaegy** [comment]
https://applemapsgutenbergblock.development.arvernus.info/?rest_route=/AppleMapKit/v1/GetJWT/

If I replace `wp-json/` with `?rest_route=/` it also seems to work  👍

**Comment by fabiankaegy** [comment]
should be solved in [1.0.7](https://github.com/Arvernus/arvernus-apple-maps-block/releases/tag/1.0.7)
