### ISSUE TITLE
selecting the block by clicking on it

### ISSUE THREAD

**Issue by DaThaoTran** [Arvernus/arvernus-apple-maps-block#6]
**Is your feature request related to a problem? Please describe.**
Whenever you want to select the arvernus apple maps block you can't just click on it, but you'll have to click and hold the six-dot-grid near the top-left corner of each block. First, I didn't understand why I wasn't able to select the block, because in regard to other blocktypes (text, picture) clicking on them works to choose them. Now that I know how to select the arvernus apple maps block, it is a little bit inconvenient to always click the six-dot-grid.

**Describe the solution you'd like**
I'd like to be able to choose the arverus apple maps block by clicking on it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/829536738800055/1117404920623885)

**Comment by fabiankaegy** [comment]
should be solved in [1.0.7](https://github.com/Arvernus/arvernus-apple-maps-block/releases/tag/1.0.7)
