### ISSUE TITLE
clicking in area outside of the block will set everything back to default

### ISSUE THREAD

**Issue by DaThaoTran** [Arvernus/arvernus-apple-maps-block#8]
**Is your feature request related to a problem? Please describe.**
Whenever you e.g. change the map type, zoom in or out or go to a different place as you typed in in the sidebar and then click in an area outside of the block, all changes you made are set back to the default setting (as set in the sidebar). 

**Describe the solution you'd like**
The changes made in the arvernus apple maps block should automatically also be saved.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/829536738800055/1117409459589024)

**Comment by fabiankaegy** [comment]
should be solved in [1.0.7](https://github.com/Arvernus/arvernus-apple-maps-block/releases/tag/1.0.7)
